//
//  VoiceResponse.swift
//  Telesign
//
//  Created by Andrew Edwards on 7/29/17.
//
//

public struct TelesignVoiceResponse: TelesignModel {
    /// A 32-digit hex value used to identify the web service request. The value is unique to each web service request, is randomly generated by TeleSign, and is returned in the response message immediately following the web service request.
    public var referenceId: String
    /// The voice tag you selected for language appears here. If you did not use this parameter, the default f-en-US is displayed.
    public var voice: VoiceLanguageOrUserInputResponse
    /// An object that describes the status of your transaction.
    public var status: Status
    
    public enum CodingKeys: String, CodingKey {
        case voice
        case status
        case referenceId = "reference_id"
    }
}
