//
//  ScoreResponse.swift
//  Telesign
//
//  Created by Andrew Edwards on 7/25/17.
//
//

public struct TelesignScoreResponse: TelesignModel {
    /// A 32-digit hex value used to identify the web service request. The value is unique to each web service request, is randomly-generated by TeleSign, and is returned in the response message immediately following the web service request.
    public var referenceId: String
    /// An object that describes the status of your transaction.
    public var status: Status
    /// An object containing details about the numbering attributes of the specified phone number.
    public var numbering: Numbering
    /// An object containing details about the phone type.
    public var phoneType: PhoneType
    /// /// An object containing geographical location information associated with the phone number.
    public var location: Location
    /// An object that describes the risk score for the phone number specified in the request.
    public var risk: Risk
    /// An object containing information about the company that provides telecommunications services for the phone number.
    public var carrier: Carrier
    
    public enum CodingKeys: String, CodingKey {
        case referenceId = "reference_id"
        case status
        case numbering
        case phoneType = "phone_type"
        case location
        case risk
        case carrier
    }
}
