//
//  MessageResponse.swift
//  Telesign
//
//  Created by Andrew Edwards on 7/21/17.
//
//

public struct TelesignMessageResponse: TelesignModel {
    /// A 32-digit hex value used to identify the web service request. The value is unique to each web service request, is randomly generated by TeleSign, and is returned in the response message immediately following the web service request.
    public var referenceId: String
    /// An object that describes the status of your transaction.
    public var status: Status
    
    public enum CodingKeys: String, CodingKey {
        case referenceId = "reference_id"
        case status
    }
}
